services:
 - crond # CronJob Deomen service
 - getty # Getty on tty1
 - dbus # D-Bus System Message Bus
 - ntpd # Network Time Service
 - rhel-domainname # Exited  Read and set NIS domainname from /etc/sysconfig/network
 - rhel-readonly # Configure read-only root support
 - rsyslog # System Logging Service
 - serial-getty # Serial Getty on ttyS0
 - sshd # OpenSSH server daemon
